from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from commons.types.events import DomainEvent


class UnitOfWork(Protocol):
    """Store-agnostic — owns the transaction and domain-event collection,
    says nothing about a specific database (spec Section 7.2)."""

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, *exc: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def track(self, aggregate: object) -> None: ...
    def collect_new_events(self) -> Iterable[DomainEvent]: ...
